version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    open-pull-requests-limit: 100

  - package-ecosystem: "terraform"
    directories:
      - "/infrastructure"
      - "/infrastructure/modules/*"
      - "/bootstrap"
      - "/virusscanner/terraform"
      - "/backup-vault/teraform"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    open-pull-requests-limit: 20
