name: Setup AWS
description: Assume role
inputs:
  role-to-assume:
    description: "The IAM role to assume"
    required: true
  aws-region:
    description: "AWS region"
    required: true
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ github.event.inputs.role-to-assume }}
        aws-region: ${{ github.event.inputs.aws-region }}
        role-skip-session-tagging: true
        mask-aws-account-id: true

    - name: View AWS Role
      run: aws sts get-caller-identity
      shell: bash
