name: "Terraform Plan & Apply"

description: "Run Terraform plan & Apply for a given component"

inputs:
  git_ref:
    description: "Branch, tag or SHA to deploy"
    required: true

  aws_assume_role:
    description: "AWS IAM Role to assume"
    required: true

  aws_region:
    description: "AWS Region to use"
    required: true

  terraform_version:
    description: "Terraform version to use"
    required: false
    default: "1.13.3"

  backend_conf:
    description: "Terraform backend config file"
    required: true

  working_directory:
    description: "Terraform working directory"
    required: false
    default: "./infrastructure"

  env_or_sandbox_name:
    description: "Environment or Sandbox name [a-z0-9]{1,8}"
    required: true

  tf_vars_file:
    description: "Terraform variables file"
    required: true


runs:
  using: "composite"
  steps:
    # - name: Checkout Branch
    #   uses: actions/checkout@v5
    #   with:
    #     ref: ${{ inputs.git_ref }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.aws_assume_role }}
        role-skip-session-tagging: true
        aws-region: ${{ inputs.aws_region }}
        mask-aws-account-id: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Initialise Terraform
      # id: init
      run: terraform init -backend-config=${{ inputs.backend_conf }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Select Terraform Workspace
      # id: workspace
      run: terraform workspace select -or-create ${{ inputs.env_or_sandbox_name }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Run Terraform Plan
      # id: plan
      run: |
        terraform plan -input=false -no-color -var-file="${{ inputs.tf_vars_file }}" -out tf.plan
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Run Terraform Apply
      run: terraform apply -auto-approve -input=false tf.plan
      working-directory: ${{ inputs.working_directory }}
      shell: bash
