environment                         = "dev"
owner                               = "nhse/ndr-team"
domain                              = "access-request-fulfilment.patient-deductions.nhs.uk"
certificate_domain                  = "access-request-fulfilment.patient-deductions.nhs.uk"
certificate_subdomain_name_prefix   = "api-"