#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# git stash push --staged            # Stash staged changes
# git stash                          # Stash everything else
# git stash pop stash@{1}  # Restore staged changes stash
# make pre-commit
# RESULT=$?
# if [ $RESULT -ne 0 ]; then
#   git stash pop -q
#   exit 1;
# fi
# git add --all
# git stash pop -q