#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

ALLCHANGES=$(git status --porcelain=v1 2>/dev/null | wc -l)       
if [ $ALLCHANGES -eq 0 ]; then
  printf "No staged changes, exiting\n"
  exit 1;
fi
git stash -- $(git diff --staged --name-only)  
WIPCHANGES=$(git status --porcelain=v1 2>/dev/null | wc -l)             
if [ $WIPCHANGES -ne 0 ]; then
  git stash
  git stash pop stash@{1} -q
else
  git stash pop stash@{0} -q
fi
make pre-commit
RESULT=$?
if [ $RESULT -ne 0 ]; then
  git stash pop -q
  printf "Error in make file, exiting\n"
  exit 1;
fi
git add --all
if [ $WIPCHANGES -ne 0 ]; then
  git stash pop -q
fi