name: 'Z-BASE: Cleanup - Workspace'

on:
  workflow_call:
    inputs:
      git_ref:
        description: 'The branch, tag or SHA'
        required: true
        type: string
      sandbox_name:
        description: 'The sandbox name'
        required: true
        type: string
      environment:
        description: "GitHub Environment name"
        required: true
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  view_action_parameters:
    name: View Deploy all input variables
    runs-on: ubuntu-latest
    steps:
      - name: Display client passed variables
        run: |
          echo Sandbox name: ${{ inputs.sandbox_name }}
          echo Git branch/tag/sha: ${{ inputs.git_ref }}
          echo Environment: ${{ inputs.environment }}

  cleanup_process:
    name: Run Cleanup Versions script
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: 'nhsconnect/national-document-repository-infrastructure'
          ref: ${{ inputs.git_ref }}
          fetch-depth: '0'

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Make virtual environment
        run: |
          python3 -m venv ./venv
          ./venv/bin/pip3 install --upgrade pip
          ./venv/bin/pip3 install boto3==1.33.11

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Run Version Cleanup Script
        run: |
          ./venv/bin/python3 scripts/cleanup_versions.py ${{ inputs.sandbox_name }}
