name: "Z-BASE: Deploy - Workspace"

on:
  workflow_call:
    inputs:
      workspace:
        description: The terraform workspace being deployed.
        type: string
        required: true
      branch:
        description: The branch to be deployed.
        type: string
        required: true
      environment:
        description: The environment to deploy to.
        type: string
        required: true
      aws-region:
        description: AWS region
        type: string
        required: true
      tf-vars:
        description: TF vars file
        type: string
        required: true
    secrets:
      AWS_ASSUME_ROLE:
        description: The IAM role to assume
        required: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform--init:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Debug AWS Inputs
        run: |
          echo "Role to assume: ${{ secrets.AWS_ASSUME_ROLE }}"
          echo "AWS Region: ${{ inputs.aws-region }}"
        shell: bash

      - name: Configure AWS
        uses: ./.github/actions/aws-setup
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      - name: Configure Terraform
        uses: ./.github/actions/terraform

      - name: Terraform Init
        id: terraform_init
        run: terraform init -backend-config=backend.conf
        working-directory: ./infrastructure
        shell: bash

  terraform--workspace:
    needs: terraform--init
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Configure AWS
        uses: ./.github/actions/aws-setup
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      - name: Configure Terraform
        uses: ./.github/actions/terraform

      - name: Terraform Set Workspace
        id: terraform_workspace
        run: terraform workspace select -or-create ${{ inputs.workspace }}
        working-directory: ./infrastructure
        shell: bash

  terraform--plan:
    needs: terraform--workspace
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Configure AWS
        uses: ./.github/actions/aws-setup
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      - name: Configure Terraform
        uses: ./.github/actions/terraform

      - name: Terraform Plan
        id: terraform_plan
        run: |
          terraform plan -input=false -no-color -var-file="${{ inputs.tf-vars }}" -out tf-main.plan
        working-directory: ./infrastructure
        shell: bash
