name: 'Remove Lambda@Edge Associations'

on:
  workflow_call:
    inputs:
      sandbox_workspace:
        description: 'The sandbox workspace name'
        required: true
        type: string
      environment:
        required: true
        type: string
      lambda_function_name:
        description: 'The sandbox workspace name'
        required: true
        type: string
      python_version:
        description: 'Version of Python to run the cleanup script against'
        required: true
        type: 'string'
      build_branch:
        description: 'Feature branch to push to sandbox.'
        required: true
        type: 'string'
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write # Required for requesting the JWT
  contents: read # Required for actions/checkout

jobs:
  remove_edge_associations:
    name: Remove Lambda@Edge Associations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Display passed variables
        run: |
          echo Python Version: ${{ inputs.python_version }}
          echo Build Branch: ${{ inputs.build_branch }}
          echo Environment: ${{ inputs.environment }}
          echo Sandbox: ${{ inputs.sandbox_workspace }}
          echo Lambda Function Name: ${{ inputs.lambda_function_name }}

      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: 'nhsconnect/national-document-repository-infrastructure'
          ref: ${{ inputs.build_branch }}
          fetch-depth: '0'

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python_version }}

      - name: Configure AWS Credentials for ${{ vars.AWS_REGION }}
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Get CloudFront Distribution ID
        id: cloudfront
        run: |
          aws cloudfront list-distributions > distributions.json
          distribution_id=$(jq -r --arg origin_id "${{ inputs.sandbox_workspace }}-lloyd-george-store" \
          '.DistributionList.Items[] | select(.Origins.Items[].Id==$origin_id) | .Id' distributions.json | head -n 1)

          if [ -z "$distribution_id" ]; then
            echo "No distribution found for origin ID: ${{ inputs.sandbox_workspace }}-lloyd-george-store"
          else
            echo "Distribution ID found: $distribution_id"
          fi
          
          echo "DISTRIBUTION_ID=$distribution_id" >> $GITHUB_ENV

      - name: Install Python Dependencies
        if: env.DISTRIBUTION_ID != ''
        run: |
          python3 -m venv ./venv
          ./venv/bin/pip3 install --upgrade pip boto3==1.33.11

      - name: Remove Lambda@Edge & CloudFront Associations
        if: env.DISTRIBUTION_ID != ''
        run: ./venv/bin/python3 -u scripts/remove_edge_associations.py
        env:
          DISTRIBUTION_ID: ${{ env.DISTRIBUTION_ID }}
          LAMBDA_FUNCTION_NAME: ${{ inputs.lambda_function_name }}
