name: 'Remove Lambda@Edge Associations'

on:
  workflow_call:
    inputs:
      sandbox_workspace:
        description: 'The sandbox workspace name'
        required: true
        type: string
      aws_region:
        description: 'AWS Region to use for the Lambda and CloudFront operations'
        required: true
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true # Ensure the secret is declared here

permissions:
  contents: read
  id-token: write

jobs:
  remove_edge_associations:
    name: Remove Lambda@Edge Associations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ inputs.aws_region }}

      - name: Get CloudFront Distribution ID
        id: cloudfront
        run: |
          aws cloudfront list-distributions > distributions.json
          distribution_id=$(jq -r --arg origin_id "${{ inputs.sandbox_workspace }}-lloyd-george-store" \
          '.DistributionList.Items[] | select(.Origins.Items[].Id==$origin_id) | .Id' distributions.json | head -n 1)

          echo "Distribution ID found: $distribution_id"
          echo "DISTRIBUTION_ID=$distribution_id" >> $GITHUB_ENV

      - name: Install Python and Dependencies
        run: |
          python3 -m venv ./venv
          ./venv/bin/pip3 install --upgrade pip boto3==1.33.11

      - name: Remove Lambda@Edge & CloudFront Associations
        run: ./venv/bin/python3 -u scripts/remove_edge_associations.py ${{ inputs.sandbox_workspace }}
        env:
          LAMBDA_FUNCTION_NAME: '${{ inputs.sandbox_workspace }}_EdgePresignLambda'
