name: 'Remove Lambda@Edge Associations'

on:
  workflow_call:
    inputs:
      build_branch:
        description: 'Feature branch to push to sandbox.'
        required: true
        type: 'string'
      environment:
        description: 'Which environment should this run against'
        required: true
        type: 'string'
      python_version:
        description: 'Version of Python to run the cleanup script against'
        required: true
        type: 'string'
      sandbox_workspace:
        description: 'The sandbox workspace name'
        required: true
        type: string
      aws_region:
        description: 'AWS Region to use for the Lambda and CloudFront operations'
        required: true
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true # Ensure the secret is declared here

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  view_action_parameters:
    name: View Deploy all input variables
    runs-on: ubuntu-latest
    steps:
      - name: Display client passed variables
        run: |
          echo Python Version: ${{ inputs.python_version }}
          echo Build Branch: ${{ inputs.build_branch }}
          echo Environment: ${{ inputs.environment }}
          echo Sandbox: ${{ inputs.sandbox_workspace }}
          echo Region: ${{ inputs.aws_region }}

  cleanup_process:
    name: Run Cleanup Versions script
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

  remove_edge_associations:
    name: Remove Lambda@Edge Associations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ inputs.aws_region }}

      - name: Get CloudFront Distribution ID
        id: cloudfront
        run: |
          aws cloudfront list-distributions > distributions.json
          distribution_id=$(jq -r --arg origin_id "${{ inputs.sandbox_workspace }}-lloyd-george-store" \
          '.DistributionList.Items[] | select(.Origins.Items[].Id==$origin_id) | .Id' distributions.json | head -n 1)

          echo "Distribution ID found: $distribution_id"
          echo "DISTRIBUTION_ID=$distribution_id" >> $GITHUB_ENV

      - name: Install Python and Dependencies
        run: |
          python3 -m venv ./venv
          ./venv/bin/pip3 install --upgrade pip boto3==1.33.11

      - name: Remove Lambda@Edge & CloudFront Associations
        run: ./venv/bin/python3 -u scripts/remove_edge_associations.py ${{ inputs.sandbox_workspace }}
        env:
          LAMBDA_FUNCTION_NAME: '${{ inputs.sandbox_workspace }}_EdgePresignLambda'
