name: "Deploy - Test"

run-name: "${{ github.event.inputs.git_ref }}"

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: "Branch, tag or SHA to deploy"
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform_plan_apply:
    name: Terraform Plan/Apply (ndr-test)
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.git_ref}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false

      - name: Initialise Terraform
        id: init
        run: terraform init -backend-config=backend-test.conf
        working-directory: ./infrastructure
        shell: bash

      - name: Select Terraform Workspace
        id: workspace
        run: terraform workspace select -or-create ${{ secrets.AWS_WORKSPACE }}
        working-directory: ./infrastructure
        shell: bash

      - name: Check Terraform Formatting
        run: terraform fmt -check
        working-directory: ./infrastructure

      - name: Run Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -var-file="${{vars.TF_VARS_FILE}}" -out tf.plan
        working-directory: ./infrastructure
        shell: bash

      - name: Run Terraform Apply
        run: terraform apply -auto-approve -input=false tf.plan
        working-directory: ./infrastructure
