name: 'Git - Rename Tag'

on:
  workflow_dispatch:
    inputs:
      old_tag:
        description: 'Numerical only e.g. 1.0.0'
        required: true
        type: 'string'
      new_tag:
        description: 'Numerical only e.g. 1.1.0'
        required: true
        type: 'string'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  tag_renaming_process:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.old_tag}}
      
      - name: Check SHA
        run:  echo git log -1 '--format=format:%H'

      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ github.event.inputs.new_tag}}',
      #         sha: context.sha
      #       })
