name: 'Destroy (Select Account) Environment'

on:
  workflow_dispatch:
    inputs:
      sandboxWorkspace:
        description: "Which Sandbox to push destroy."
        required: true
        type: "string"
      terraformVars:
        default: "dev.tfvars"
        description: "Which vars file is required? For test, change to test.tfvars"
        required: true
        type: "string"
      environment:
        default: "development"
        description: "Which environment should this run against"
        required: true
        type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
    
jobs:
  terraform_process:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
        role-skip-session-tagging: true
        aws-region: ${{ vars.AWS_REGION }}
      
    - name: View AWS Role
      run: aws sts get-caller-identity

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.4
        terraform_wrapper: false
      
    - name: Terraform Init
      id: init
      run: terraform init -backend-config=backend.conf
      working-directory: ./infrastructure 
      shell: bash

    - name: Terraform Set Workspace
      id: workspace
      run:  terraform workspace select ${{ github.event.inputs.sandboxWorkspace}}
      working-directory: ./infrastructure 
      shell: bash
    
    - name: Terraform Destroy 
      run: terraform destroy -auto-approve -var-file="${{ github.event.inputs.terraformVars }}"
      working-directory: ./infrastructure
        
        
