# .github/workflows/terraform-dev
name: 'Terraform - Development'

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

permissions:
  contents: read
  pull-requests: write
    
jobs:
  terraform_process:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.4
        terraform_wrapper: false
  
    - name: Terraform Set Workspace
      id: init
      run:  terraform workspace select ${{ secrets.AWS_WORKSPACE }}
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./infrastructure 
      shell: bash

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./infrastructure 
      shell: bash
      
      # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -var-file="dev.tfvars" -out tf.plan
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./infrastructure
      shell: bash
        
        
