# .github/workflows/terraform-dev
name: 'Deploy Feature Branch to Sandbox'

on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: 'Feature branch to push to sandbox.'
        required: true
        type: 'string'
      sandboxWorkspace:
        description: 'Which Sandbox to push to.'
        required: true
        type: 'string'
      environment:
        default: 'development'
        description: 'Which environment should this run against'
        required: true
        type: 'string'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform_process:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.buildBranch}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: View AWS Role
        run: aws sts get-caller-identity

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.conf
        working-directory: ./infrastructure
        shell: bash

      - name: Terraform Set Workspace
        id: workspace
        run: terraform workspace select -or-create ${{ github.event.inputs.sandboxWorkspace}}
        working-directory: ./infrastructure
        shell: bash

        # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./infrastructure

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -var-file="${{vars.TF_VARS_FILE}}" -out tf.plan > plan_output.txt 2>&1
          terraform show -no-color tf.plan > tfplan.txt 2>&1
  
          # Mask sensitive URLs in the Terraform Plan output
          grep -Eo 'https://[a-zA-Z0-9.-]+\.execute-api\.[a-zA-Z0-9.-]+\.amazonaws\.com/[a-zA-Z0-9/._-]*' tfplan.txt | while read -r api_url; do
            if [ -n "$api_url" ]; then
              echo "::add-mask::$api_url"
            fi
          done || echo "No api URLs found to mask."
  
          # Mask Lambda invocation URLs
          grep -Eo 'https://[a-zA-Z0-9.-]+\.lambda\.amazonaws\.com/[a-zA-Z0-9/._-]+' tfplan.txt | while read -r lambda_url; do
            if [ -n "$lambda_url" ]; then
              echo "::add-mask::$lambda_url"
            fi
          done || echo "No Lambda URLs found to mask."
  
          # Mask AWS account IDs (12-digit numbers)
          grep -Eo '[0-9]{12}' tfplan.txt | while read -r account_id; do
            if [ -n "$account_id" ]; then
              echo "::add-mask::$account_id"
            fi
          done || echo "No Account IDs found to mask."
  
          # Mask PEM-encoded certificate blocks
          grep -Poz '(?s)-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----' tfplan.txt | while read -r cert_block; do
            if [ -n "$cert_block" ]; then
              echo "::add-mask::$cert_block"
            fi
          done || echo "No PEM certificates found to mask."
  
          # Mask GitHub secrets
          echo "::add-mask::${{ secrets.AWS_ASSUME_ROLE }}"
          echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"
  
          # Mask Terraform variables
          echo "::add-mask::${{ vars.TF_VARS_FILE }}"
  
          # Output the sanitized plan to logs
          cat plan_output.txt
  
          echo "summary=$(grep -E 'Plan: [0-9]+ to add, [0-9]+ to change, [0-9]+ to destroy\.|No changes\. Your infrastructure matches the configuration\.' tfplan.txt | sed 's/.*No changes\. Your infrastructure matches the configuration/Plan: no changes/g' | sed 's/.*Plan: //g' | sed 's/\..*//g')" >> $GITHUB_OUTPUT
        working-directory: ./infrastructure
        shell: bash

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false tf.plan
        working-directory: ./infrastructure
