# .github/workflows/terraform-dev
name: 'Deploy Feature Branch to Sandbox with Dispatch'

on:
  workflow_dispatch:
    inputs:
      build_branch:
        default: "main"
        description: "Feature branch to push to sandbox."
        required: true
        type: "string"
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
      terraform_vars:
        default: "dev.tfvars"
        description: "Which vars file is required? For test, change to test.tfvars"
        required: true
        type: "string"
      environment:
        default: "development"
        description: "This is the environement the action will run in, for ndr-test, set to 'test'"
        required: true
        type: "string"
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout
  repository-projects: write
    
jobs:
  terraform_process:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment}}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.build_branch}}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
        role-skip-session-tagging: true
        aws-region: ${{ vars.AWS_REGION }}
        mask-aws-account-id: true
      
    - name: View AWS Role
      run: aws sts get-caller-identity

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.4
        terraform_wrapper: false
      
    - name: Terraform Init
      id: init
      run: terraform init -backend-config=backend.conf
      working-directory: ./infrastructure 
      shell: bash

    - name: Terraform Set Workspace
      id: workspace
      run:  terraform workspace select ${{ github.event.inputs.sandbox}}
      working-directory: ./infrastructure 
      shell: bash
      
      # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./infrastructure 

    - name: Terraform Plan
      id: plan
      run: |
        # Run Terraform plan, suppressing direct output
        terraform plan -input=false -no-color -var-file="${{ vars.TF_VARS_FILE }}" -out=tf.plan 2> plan_exec_log.txt

        # Convert binary plan to human-readable output
        terraform show -no-color tf.plan > tfplan.txt

        # Mask PEM certificates (if present in tfplan.txt)
        awk 'BEGIN{cert=""}
          /-----BEGIN CERTIFICATE-----/{cert=$0; in_cert=1; next}
          /-----END CERTIFICATE-----/{cert=cert"\n"$0; print cert; cert=""; in_cert=0; next}
          in_cert{cert=cert"\n"$0}' tfplan.txt | while IFS= read -r cert_block; do
            if [ -n "$cert_block" ]; then
              echo "::add-mask::$cert_block"
            fi
        done || echo "No certificate blocks found to mask."

        # Log the sanitized tfplan.txt for GitHub Actions output
        echo '--- Terraform Plan Summary ---'
        cat tfplan.txt

        # Extract plan summary (add/change/destroy)
        echo "summary=$(grep -E 'Plan: [0-9]+ to add, [0-9]+ to change, [0-9]+ to destroy\.|No changes\. Your infrastructure matches the configuration\.' tfplan.txt | sed 's/.*No changes\. Your infrastructure matches the configuration/Plan: no changes/g' | sed 's/.*Plan: //g' | sed 's/\..*//g')" >> $GITHUB_OUTPUT
      working-directory: ./infrastructure
      shell: bash
    
    - name: Terraform Apply 
      run: terraform apply -auto-approve -input=false tf.plan
      working-directory: ./infrastructure

  run_main_repo_deploy_lambdas:
    name: Deploy Lambdas on NDR Functional Repo
    needs: ['terraform_process']
    uses: nhsconnect/national-document-repository/.github/workflows/lambdas-deploy-feature-to-sandbox.yml@main
    with:
      build_branch: main
      sandbox: ${{ inputs.sandbox }}
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
  
  run_main_repo_deploy_ui:
    name: Deploy Lambdas on NDR Functional Repo
    needs: ['terraform_process']
    uses: nhsconnect/national-document-repository/.github/workflows/ui-deploy-feature-to-sandbox-manual.yml@main
    with:
      build_branch: main
      sandbox: ${{ inputs.sandbox }}
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

