name: 'Tool: Rename Git Tag'

run-name: "${{ github.event.inputs.old_tag }} -> ${{ github.event.inputs.new_tag }}"

on:
  workflow_dispatch:
    inputs:
      old_tag:
        description: 'Existing tag'
        required: true
        type: 'string'
        default: 1.0.0
      new_tag:
        description: 'Replacement tag'
        required: true
        type: 'string'
        default: 1.1.0

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  tag_renaming_process:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.old_tag }}
          fetch-depth: 0
      
      - name: Check SHA
        id: get-sha
        run: |
          echo "BRANCH_SHA=$(git log -1 '--format=format:%H')">> $GITHUB_OUTPUT
      
      - name: Check SHA value
        run: |
          echo Branch SHA: ${{ steps.get-sha.outputs.BRANCH_SHA }}
          
      - name: Overwrite tag
        uses: actions/github-script@v8
        with:
          script: |
            console.log(context)
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.new_tag }}',
              sha: '${{ steps.get-sha.outputs.BRANCH_SHA }}'
            })
